### PR TITLE
Use URL constructor instead of regex to check for valid URL

### LINKED ISSUE #545: use of credentials in embeded PDF doesn't work
I have a PDF which I'm trying to embed using the syntax:

```
{%pdf https://myserver.net/public/PDF/Document.pdf %}
```

This works.  However, the PDF is stored on a WebDAV server which requires authentication.
When I try to embed the authentication information:

```
{%pdf https://public:public@myserver.net/public/PDF/Document.pdf %}
```

The PDF tag, then doesn't load.

I guess that something is failing in parsing the `user:password@` stanza.

### PR DESCRIPTION
**Pull request by davidmehren**
Fixes #545
Basic auth-regex from https://gist.github.com/dperini/729294

Co-authored-by: Yannick Bungers <git@innay.de>
Signed-off-by: David Mehren <git@herrmehren.de>

### CODE REVIEW

**Review by ErikMichelson — APPROVED** [review]

File: public/js/extra.js [hunk 1]
```diff
@@ -179,6 +179,7 @@ function slugifyWithUTF8 (text) {
 
 export function isValidURL (str) {
   const pattern = new RegExp('^(https?:\\/\\/)?' + // protocol
+        '(?:\\S+(?::\\S*)?@)?' + // basic auth
```
Comment (SISheogorath) [inline public/js/extra.js:182]: How about we simplify the whole function to a native browser interface (which is missing from IE11, but otherwise fine):

```
export function isValidURL (str) {
  try {
    new URL(str)
  } catch(e) {
    return false
  }
 
  return true
}
```

Because the regex you provide there will eat itself, probably ending up in yet another RegexDoS.

Comment (davidmehren) [reply public/js/extra.js]: Great idea, done!

**Comment by ErikMichelson** [comment]
I don't think that this change made it better. The URL-constructor allows just too much to be useful in this context. For example the following "URL" is perfectly valid with this approach: `somerandomwords:`.
Maybe at least add a check for the protocol to be either `http`, `https` or `ftp`.

**Comment by SISheogorath** [comment]
@ErikMichelson Good point. But at least we can now use the object representation and no longer need to parse things ourselves :D

**Comment by davidmehren** [comment]
I added a check for the used protocol, but decided to support `http` and `https` to not accidentally break someones HTTP-only deployment.

**Review by SISheogorath — APPROVED** [review]
LGTM much cleaner :)

**Review by ErikMichelson — APPROVED** [review]
